feat(config): explain_error window use hover_action config
mrcjkb/rustaceanvim pull request #133
Opened 2024-01-07 13:31 UTC by saying121

By utilizing the existing optionscan avoid user modifying their config.I think it would be better to do it this way.

2024-01-07 14:41 UTC, mrcjkb requested changes
Thanks :smile: 

I don't think it makes sense to reuse the `tools.hover_actions` config, as the name of the field would be inconsistent.

Instead, I would suggest the following:

- Use a `tools.float_win_config` option, which we apply to all floating windows created by this plugin:

```lua
---@field float_win_config table Options applied to floating windows. See |api-win_config|.
```

To keep backward compatibility, we would have to use the `tools.hover_actions` options if they exist. But we can remove them from the docs in `config/init.lua`.

For this, we would also have to update config validations, and add a changelog entry (`## [Unreleased], ### Added` section).

2024-01-07 14:49 UTC, saying121 commented
Got it.

2024-01-08 08:42 UTC, mrcjkb requested changes

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/init.lua
> +---@field replace_builtin_hover ? boolean whether use plugin's hover to replace Neovim's built-in `vim.lsp.buf.hover`.
```suggestion
---@field replace_builtin_hover? boolean Whether to replace Neovim's built-in `vim.lsp.buf.hover` with hover actions. Default: `true`
```

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/init.lua
> +---@field float_win_config table Options applied to floating windows. See `vim.lsp.util.open_floating_preview`.
issue:

- The field should be optional (`?` after the field name).
- Link to `api-win_config` using vimdoc syntax (vimdoc is generated from these lua docs).

```suggestion
---@field float_win_config? table Options applied to floating windows. See |api-win_config|.
```

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/init.lua
> ----@field hover_actions? RustaceanHoverActionsOpts Options for hover actions
issue: this is not backward compatible.

We should keep the `hover_actions` field and the `RustaceanHoverActionsOpts` class, but the class should have all fields removed, except for `replace_builtin_hover`.

(This needs to be reflected in the changelog)

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +      -- the border that is used for the hover window.
issue: we should remove all fields that have been moved to `float_win_config` from the default `hover_actions`

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +    replace_builtin_hover = true,
issue: let's keep this in `hover_actions`, to avoid polluting namespaces.

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +    ---@class table Options applied to floating windows.
issue:

```suggestion
    ---@type table Options applied to floating windows.
```

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +if opts.tools.hover_actions == nil then
issue: after addressing my previous comments, this can be removed.

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/hover_actions.lua
> +  local win_opt = config.tools.float_win_config
issue: After addressing my previous comments, this should be changed to

```lua
  -- NOTE: This is for backward compatibility
  local win_opt = vim.tbl_deep_extend('force', config.tools.float_win_config, config.tools.hover_actions)
```

2024-01-08 08:42 UTC, mrcjkb commented on lua/rustaceanvim/lsp.lua
> -  if config.tools.hover_actions.replace_builtin_hover then
issue: after addressing my previous comments, this change can be reverted.

2024-01-08 14:25 UTC, mrcjkb submitted a review, later dismissed

2024-01-08 14:25 UTC, mrcjkb commented on lua/rustaceanvim/config/check.lua
> +  end
```suggestion
  ok, err = validate('tools.hover_actions', {
    replace_builtin_hover = { hover_actions.replace_builtin_hover, 'boolean' },
  })
  if not ok then
    return false, err
  end
```

2024-01-08 14:25 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +      -- the border that is used for the hover window or explain_error window
```suggestion
      -- the border that is used for floating windows
```

2024-01-08 14:25 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +      --- maximal width of the hover window or explain_error window. Nil means no max.
```suggestion
      --- maximal width of floating windows. Nil means no max.
```

2024-01-08 14:25 UTC, mrcjkb commented on lua/rustaceanvim/config/internal.lua
> +      --- maximal height of the hover window or explain_error window. Nil means no max.
```suggestion
      --- maximal height of floating windows. Nil means no max.
```

2024-01-08 14:25 UTC, mrcjkb commented on CHANGELOG.md
> +  from `hover_actions` to `float_win_config`.
```suggestion
- Config: `tools.float_win_config` for all floating Windows
  created by this plugin.
  Moved `border`, `max_width`, `max_height`, `auto_focus`
  from `hover_actions` to `float_win_config`.
  The `hover_actions` window options are still applied
  if they exist, so as not to break compatibility.
```

2024-01-08 14:45 UTC, merged