Rustc unpretty
mrcjkb/rustaceanvim pull request #192
Opened 2024-01-28 13:43 UTC by saying121

Use `rustc -Z unpretty=mir` to inspect mir and other things,
and achieve an experience similar to Rust Playground.
The rust-analyzer view does not support viewing MIR for async blocks,
but rustc can do it.

2024-01-28 14:02 UTC, mrcjkb commented
Hey :wave: 

This looks great! Thanks for the PR! :smile: 

I'll have a closer look at it later today.

2024-01-28 20:00 UTC, mrcjkb requested changes
Thanks again for this awesome PR! :heart: 

I have left some thoughts and suggestions.
Let me know if you'd like to implement them. If not, I'm happy to merge this into a feature branch and implement them myself :smile:

2024-01-29 05:11 UTC, saying121 commented on lua/rustaceanvim/commands/rustc_unpretty.lua
> +    vim.notify('please install rust parser in nvim-treesitter', vim.log.levels.ERROR)
Is there a better way to obtain the function? 
I'm not sure what to do.

2024-01-29 05:12 UTC, saying121 commented on lua/rustaceanvim/commands/init.lua
> +  rustcUnpretty = function(args)
I'm not familiar with the code structure, so I'll pass on this task.

2024-01-29 05:16 UTC, saying121 commented
I think I have done all I can do. 😄
Thanks for your work.

2024-01-29 11:01 UTC, mrcjkb approved these changes

2024-01-29 11:02 UTC, mrcjkb commented
> I think I have done all I can do. 😄 Thanks for your work.

Thanks :pray:. I'll merge it into the `rustc-unpretty-continued` branch and continue working on it from there.

2024-01-29 11:02 UTC, merged

2024-01-29 12:33 UTC, mrcjkb commented
@saying121 I've just finished the touchup and pushed a 4.1.0 release. The command is now `:Rustc unpretty`, and the config field is `tools.rustc`.

Thanks again for the awesome contribution :pray: :smile: