feat(lsp): add command to reload lsp settings
mrcjkb/rustaceanvim pull request #309
Opened 2024-03-21 22:30 UTC by GuillaumeLagrange

Following the discussion we had in #286, I found out how to reload settings using `workspace/didChangeConfiguration`.

Turns out the lsp server responds by a `workspace/configuration` where the server actually pulls the new configuration, since the server can cache configuration and decides whether it needs to actually pull the config.

`nvim` handles it, but we need to set the `client.settings` table to the new configuration before sending the `workspace/didChangeConfiguration` because it seems to be the one used by nvim to send the actual config.

I added this feature as a command because it made sense to me, let me know if it does not for you.

Once again, tested the changes on https://github.com/GuillaumeLagrange/neoconf-repro and it works for me.

Cheers

2024-03-22 09:20 UTC, mrcjkb requested changes
Thanks for the PR 😄 

This seems like a good approach.
I'll see it I can find some time to test it soon.

2024-03-22 09:20 UTC, mrcjkb commented on lua/rustaceanvim/lsp.lua
> +  vim.print('Hello from reload_settings')
issue: forgotten print statement 😀

```suggestion
```

2024-03-22 09:20 UTC, mrcjkb commented on CHANGELOG.md
> +- LSP: `RustAnalyzer reload_settings` command to reload settings without restarting.
suggestion: For consistency with the `RustLsp` commands, I would suggest camel case.

2024-03-22 10:34 UTC, GuillaumeLagrange commented
@mrcjkb I'm having troubles with the lua type checker, the [CI build fails](https://github.com/mrcjkb/rustaceanvim/actions/runs/8388093729/job/22971595899), and I can reproduce locally by running

`nix flake check --print-build-logs`

For some reason, it has trouble detecting that `client` is an `lsp.Client` class, but my lsp in nvim detects it properly with the cast.
I'm not experienced with nix at all so I cannot dig deeper that this :(

2024-03-22 11:05 UTC, mrcjkb commented
> @mrcjkb I'm having troubles with the lua type checker, the [CI build fails](https://github.com/mrcjkb/rustaceanvim/actions/runs/8388093729/job/22971595899), and I can reproduce locally by running
> 
> `nix flake check --print-build-logs`
> 
> For some reason, it has trouble detecting that `client` is an `lsp.Client` class, but my lsp in nvim detects it properly with the cast. I'm not experienced with nix at all so I cannot dig deeper that this :(

Don't worry about that. I'll fix it before merging 😀

2024-03-23 22:50 UTC, mrcjkb requested changes

2024-03-23 22:50 UTC, mrcjkb commented on lua/rustaceanvim/lsp.lua
> +    local settings = get_start_settings(vim.api.nvim_buf_get_name(bufnr), client.root_dir, config.server)
```suggestion
    local settings = get_start_settings(vim.api.nvim_buf_get_name(bufnr), client.config.root_dir, config.server)
```

2024-03-23 22:50 UTC, mrcjkb commented on lua/rustaceanvim/lsp.lua
> +    client.settings = settings
We can disable this diagnostic, as it's a lua-language-server quirk.

```suggestion
    ---@diagnostic disable-next-line: inject-field
    client.settings = settings
```

2024-03-23 22:55 UTC, mrcjkb approved these changes
Tested it, and it seems to be working well :smile:

2024-03-23 22:55 UTC, merged